version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/app-deployment
    overwrite: yes

permissions:
  - object: /home/ubuntu/app-deployment/scripts/deploy.sh
    pattern: "**"
    owner: ubuntu
    group: ubuntu
    mode: 755

hooks:
  ApplicationStart:
    - location: scripts/deploy.sh
      timeout: 300
      runas: ubuntu